spring:
    datasource:
        url: jdbc:mysql://awseb-e-8zmrqhfgtd-stack-awsebrdsdatabase-ykbbodhxecne.c98qooqka9nj.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
        username: fastcam
        password: fastcam1!
#        url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
#        username: root
#        password:
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
